### ISSUE TITLE
eid-pt is disrupting install of other brew packages due to unbrewed dylibs

### ISSUE THREAD

**Issue by ruychi** [caskroom/homebrew-eid#11]
The eid-pt formula (install package of Cartão de Cidadão) places unbrewed dylibs in /usr/local/lib, namely the /usr/local/lib/libjpeg.9.dylib.

Additionally,  there's something wrong with the jpeg libjpeg.9.dylib, which for some reason isn't keg_only, while brew's current version is 8d. 

For example, "wine"'s dependencies must be built with --universal and one of those decencies, libgphoto2, does not compile due to libjpeg.9.dylib. This means that some other packages dependency trees would need to be rebuild (or else they do not install).

Additionally, uninstalling eid-pt doesn't clean up correctly, leaving those dylibs and also some header files behind, and brew complains.

**$ brew doctor**
_Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted._

Unexpected dylibs:
/usr/local/lib/libboost_system.dylib
/usr/local/lib/libcrypto.1.0.0.dylib
/usr/local/lib/libjasper.1.0.0.dylib
/usr/local/lib/libjpeg.9.dylib
/usr/local/lib/libpteiddlg.1.61.0.dylib
/usr/local/lib/libpteidhttps.1.61.0.dylib
/usr/local/lib/libpteidlib.1.61.0.dylib
/usr/local/lib/libpteidlibopensc.1.61.0.dylib
/usr/local/lib/libssl.1.0.0.dylib
/usr/local/lib/pteidpkcs11.1.61.0.dylib

_Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:_
/usr/local/include/pteid/pteiddefines.h
/usr/local/include/pteid/pteidlib.h

**$ brew cask uninstall eid-pt**
==> Running uninstall process for eid-pt; your password may be necessary
==> Running uninstall script /usr/local/bin/pteid_uninstall.sh
Password:

**$ brew doctor**
_Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:_
/usr/local/lib/libcrypto.1.0.0.dylib
/usr/local/lib/libjasper.1.0.0.dylib
/usr/local/lib/libjpeg.9.dylib
/usr/local/lib/libssl.1.0.0.dylib

_Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:_
/usr/local/include/pteid/pteiddefines.h
/usr/local/include/pteid/pteidlib.h

**Comment by vitorgalvao** [comment]
Not much we can do about that. We simply run the `pkg` to install, and their uninsntall script to uninstall. The warnings are mostly because homebrew assumes to an extent complete ownership of `/usr/local` (and they shouldn’t).

Two things we can do: add a `caveat` (won’t fix it, but will warn users) and fix `uninstall` to be more thorough and cleanup those missed files.

For the most part, though, this issue is being brought up in the wrong place. Upstream should be contacted to fix their main issues, namely that they seem to be changing ownership of some directories, and that they’re not doing a good job of cleaning up all they left.

I ask that you try and contact them first, as [workarounds are not the solution to upstream problems](https://github.com/caskroom/homebrew-cask/issues/13201).
